spring:
  application:
    name: order

  datasource:
    url: ${ORDER_POSTGRES_URL}
    username: ${ORDER_POSTGRES_USERNAME}
    password: ${ORDER_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  config:
    import:
      - "classpath:application-eureka.yml"
      - "classpath:application-jpa.yml"
      - "classpath:application-redis.yml"
      - "classpath:application-kafka.yml"
      - "classpath:application-monitoring.yml"

server:
  port: 10013
