spring:
  application:
    name: order

  datasource:
    url: ${ORDER_POSTGRES_URL}
    username: ${ORDER_POSTGRES_USERNAME}
    password: ${ORDER_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  config:
    import:
      - "classpath:application-eureka.yml"
      - "classpath:application-jpa.yml"
      - "classpath:application-kafka.yml"
      - "classpath:application-monitoring.yml"
      - "classpath:application-circuit-breaker.yml"

server:
  port: 10013

resilience4j:
  retry:
    instances:
      performanceServiceRetry:
        baseConfig: default
      paymentServiceRetry:
        baseConfig: default

  circuitbreaker:
    instances:
      performanceServiceCircuitBreaker:
        baseConfig: default
      paymentServiceCircuitBreaker:
        baseConfig: default
