version: '3.8'

services:
  eureka-server:
    container_name: eureka-server
    image: ticketping/eureka-server:latest
    ports:
      - "10000:10000"

  gateway-server:
    container_name: gateway-server
    image: ticketping/gateway-server:latest
    env_file:
      - .env
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - "10001:10001"
    depends_on:
      auth-server:
        condition: service_started
      user-server:
        condition: service_started
      performance-server:
        condition: service_started
      order-server:
        condition: service_started
      payment-server:
        condition: service_started
      queue-manage-server:
        condition: service_started

  auth-server:
    container_name: auth-server
    image: ticketping/auth-server:latest
    env_file:
      - .env
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - "10010:10010"
    depends_on:
      eureka-server:
        condition: service_started

  user-server:
    container_name: user-server
    image: ticketping/user-server:latest
    ports:
      - "10011:10011"
    depends_on:
      eureka-server:
        condition: service_started

  performance-server:
    container_name: performance-server
    image: ticketping/performance-server:latest
    ports:
      - "10012:10012"
    depends_on:
      eureka-server:
        condition: service_started

  order-server:
    container_name: order-server
    image: ticketping/order-server:latest
    ports:
      - "10013:10013"
    depends_on:
      eureka-server:
        condition: service_started

  payment-server:
    container_name: payment-server
    image: ticketping/payment-server:latest
    ports:
      - "10014:10014"
    depends_on:
      eureka-server:
        condition: service_started

  queue-manage-server:
    container_name: queue-manage-server
    image: ticketping/queue-manage-server:latest
    ports:
      - "10015:10015"
    depends_on:
      eureka-server:
        condition: service_started

networks:
  default:
    driver: bridge