version: "3.1"
services:
  redis-master-1:
    container_name: redis-master-1
    image: redis:latest
    command: >
      redis-server --port 7001 
      --cluster-enabled yes 
      --cluster-config-file node.conf 
      --cluster-node-timeout 5000 
      --appendonly yes
      --notify-keyspace-events Ex
    ports:
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
      - "7006:7006"

  redis-master-2:
    network_mode: "service:redis-master-1"
    container_name: redis-master-2
    image: redis:latest
    command: >
      redis-server --port 7002
      --cluster-enabled yes 
      --cluster-config-file node.conf 
      --cluster-node-timeout 5000 
      --appendonly yes
      --notify-keyspace-events Ex

  redis-master-3:
    network_mode: "service:redis-master-1"
    container_name: redis-master-3
    image: redis:latest
    command: >
      redis-server --port 7003
      --cluster-enabled yes 
      --cluster-config-file node.conf 
      --cluster-node-timeout 5000 
      --appendonly yes
      --notify-keyspace-events Ex

  redis-replica-1:
    network_mode: "service:redis-master-1"
    container_name: redis-replica-1
    image: redis:latest
    command: >
      redis-server --port 7004
      --cluster-enabled yes 
      --cluster-config-file node.conf 
      --cluster-node-timeout 5000 
      --appendonly yes
      --notify-keyspace-events Ex

  redis-replica-2:
    network_mode: "service:redis-master-1"
    container_name: redis-replica-2
    image: redis:latest
    command: >
      redis-server --port 7005
      --cluster-enabled yes 
      --cluster-config-file node.conf 
      --cluster-node-timeout 5000 
      --appendonly yes
      --notify-keyspace-events Ex

  redis-replica-3:
    network_mode: "service:redis-master-1"
    container_name: redis-replica-3
    image: redis:latest
    command: >
      redis-server --port 7006 
      --cluster-enabled yes 
      --cluster-config-file node.conf 
      --cluster-node-timeout 5000 
      --appendonly yes
      --notify-keyspace-events Ex

  redis-cluster-entry:
    network_mode: "service:redis-master-1"
    image: redis:latest
    container_name: redis-cluster-entry
    command: >
      redis-cli --cluster create 
      redis-master-1:7001 redis-master-1:7002 redis-master-1:7003 
      redis-master-1:7004 redis-master-1:7005 redis-master-1:7006 
      --cluster-replicas 1 
      --cluster-yes
    depends_on:
      - redis-master-1
      - redis-master-2
      - redis-master-3
      - redis-replica-1
      - redis-replica-2
      - redis-replica-3