spring:
  application:
    name: gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-origins: ${FRONTEND_APP_URL}
            allowed-headers: "*"
            allowed-methods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS

  config:
    import:
      - "classpath:application-eureka.yml"
      - "classpath:application-redis.yml"
      - "classpath:application-monitoring.yml"

server:
  port: 10001

token-value:
  secret-key: ${USER_TOKEN_SECRET_KEY}

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 10s
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        record-exceptions:
          - java.util.concurrent.TimeoutException
          - org.springframework.cloud.gateway.support.NotFoundException
          - io.netty.channel.AbstractChannel$AnnotatedConnectException
    instances:
      authServiceCircuitBreaker:
        baseConfig: default
      userServiceCircuitBreaker:
        baseConfig: default
      performanceServiceCircuitBreaker:
        baseConfig: default
      orderServiceCircuitBreaker:
        baseConfig: default
      paymentServiceCircuitBreaker:
        baseConfig: default
      queueManageCircuitBreaker:
        baseConfig: default