spring:
  application:
    name: gateway

  config:
    import:
      - "classpath:application-eureka.yml"
      - "classpath:application-redis.yml"
      - "classpath:application-monitoring.yml"

server:
  port: 10001

token-value:
  secret-key: secret-key