spring:
  application:
    name: gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-origins: ${client.url}
            allowed-headers: "*"
            allowed-methods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS

  config:
    import:
      - "classpath:application-eureka.yml"
      - "classpath:application-redis.yml"
      - "classpath:application-monitoring.yml"

server:
  port: 10001

client:
  url: ${FRONTEND_APP_URL}

token-value:
  secret-key: ${USER_TOKEN_SECRET_KEY}

resilience4j:
  retry:
    retry-aspect-order: 2
    configs:
      default:
        max-attempts: 3
        wait-duration: 500ms
      authServiceRetry:
        retry-exceptions:
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - org.springframework.web.reactive.function.client.WebClientResponseException.ServiceUnavailable

  timelimiter:
    configs:
      default:
        timeout-duration: 15s

  circuitbreaker:
    circuit-breaker-aspect-order: 1
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 10s
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        record-exceptions:
          - java.util.concurrent.TimeoutException
          - org.springframework.cloud.gateway.support.NotFoundException
          - io.netty.channel.AbstractChannel$AnnotatedConnectException
    instances:
      userServiceCircuitBreaker:
        baseConfig: default
      performanceServiceCircuitBreaker:
        baseConfig: default
      orderServiceCircuitBreaker:
        baseConfig: default
      paymentServiceCircuitBreaker:
        baseConfig: default
      queueManageServiceCircuitBreaker:
        baseConfig: default
      authServiceCircuitBreaker:
        baseConfig: default
        record-exceptions:
          - java.util.concurrent.TimeoutException
          - org.springframework.cloud.gateway.support.NotFoundException
          - io.netty.channel.AbstractChannel$AnnotatedConnectException
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - org.springframework.web.reactive.function.client.WebClientResponseException.BadGateway
          - org.springframework.web.reactive.function.client.WebClientResponseException.GatewayTimeout
          - org.springframework.web.reactive.function.client.WebClientResponseException.TooManyRequests
          - org.springframework.web.reactive.function.client.WebClientResponseException.ServiceUnavailable