spring:
  application:
    name: gateway

  config:
    import:
      - "classpath:application-eureka.yml"
      - "classpath:application-redis.yml"
      - "classpath:application-monitoring.yml"

server:
  port: 10001

token-value:
  secret-key: secret-key

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 10s
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
    instances:
      authServiceCircuitBreaker:
        baseConfig: default
      userServiceCircuitBreaker:
        baseConfig: default
      performanceServiceCircuitBreaker:
        baseConfig: default
      orderServiceCircuitBreaker:
        baseConfig: default
      paymentServiceCircuitBreaker:
        baseConfig: default
      queueManageCircuitBreaker:
        baseConfig: default