spring:
  cloud:
    openfeign:
      circuitbreaker: enabled

resilience4j:
  retry:
    retry-aspect-order: 2
    configs:
      default:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - feign.RetryableException
          - feign.FeignException.ServiceUnavailable

  circuitbreaker:
    circuit-breaker-aspect-order: 1
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 10s
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        recordSlowCalls: true
        record-exceptions:
          - feign.RetryableException
          - feign.FeignException.GatewayTimeout
          - feign.FeignException.BadGateway
          - feign.FeignException.TooManyRequests
          - feign.FeignException.ServiceUnavailable