apiVersion: 1
groups:
  - orgId: 1
    name: TicketPing
    folder: TicketPing
    interval: 1m
    rules:
      - uid: fe2ufg46pdou8a
        title: CPU Usage Over 50% (Queue-manage-server)
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: PBFA97CFB590B2093
            model:
              disableTextWrap: false
              editorMode: builder
              expr: system_cpu_usage
              fullMetaSearch: false
              includeNullMetadata: true
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
              useBackend: false
          - refId: C
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0.5
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 1m
        annotations: {}
        labels: {}
        isPaused: false
        notification_settings:
          receiver: TicketPing-Discord
