spring:
  application:
    name: auth

  config:
    import:
      - "classpath:application-eureka.yml"
      - "classpath:application-redis.yml"
      - "classpath:application-monitoring.yml"
      - "classpath:application-circuit-breaker.yml"

server:
  port: 10010

jwt:
  secret: ${JWT_SECRET_KEY}
  accessToken:
    expiration: 1800000  # 30분
  refreshToken:
    expiration: 604800000  # 7일

resilience4j:
  circuitbreaker:
    instances:
      userServiceCircuitBreaker:
        baseConfig: default