spring:
  application:
    name: auth

  config:
    import:
      - "classpath:application-redis.yml"

server:
  port: 10010

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:10000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  prometheus:
    enabled: true

jwt:
  secret: ${JWT_SECRET_KEY}