spring:
  application:
    name: payment

  datasource:
    url: ${PAYMENT_POSTGRES_URL}
    username: ${PAYMENT_POSTGRES_USERNAME}
    password: ${PAYMENT_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  config:
    import:
      - "classpath:application-eureka.yml"
      - "classpath:application-jpa.yml"
      - "classpath:application-kafka.yml"
      - "classpath:application-monitoring.yml"

server:
  port: 10014

toss:
  payment:
    widget-secret-key: ${TOSS_PAYMENT_WIDGET_SECRET_KEY}
    payment-confirm-url: ${TOSS_PAYMENT_CONFIRM_URL}