spring:
  application:
    name: payment

  datasource:
    url: jdbc:postgresql://localhost:5432/ticketping
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  config:
    import:
      - "classpath:application-jpa.yml"
      - "classpath:application-kafka.yml"

server:
  port: 10024

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  prometheus:
    enabled: true