spring:
  application:
    name: performance

  datasource:
    url: ${PERFORMANCE_POSTGRES_URL}
    username: ${PERFORMANCE_POSTGRES_USERNAME}
    password: ${PERFORMANCE_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  config:
    import:
      - "classpath:application-eureka.yml"
      - "classpath:application-jpa.yml"
      - "classpath:application-redis.yml"
      - "classpath:application-monitoring.yml"

server:
  port: 10012

