spring:
  application:
    name: eureka-server

server:
  port: 10000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER}
  instance:
    hostname: eureka-server