spring:
  application:
    name: user

  datasource:
    url: jdbc:postgresql://user-db:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  config:
    import:
      - "classpath:application-eureka.yml"
      - "classpath:application-jpa.yml"
      - "classpath:application-monitoring.yml"

server:
  port: 10011
