spring:
  application:
    name: user

  datasource:
    url: ${USER_POSTGRES_URL}
    username: ${USER_POSTGRES_USERNAME}
    password: ${USER_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  config:
    import:
      - "classpath:application-eureka.yml"
      - "classpath:application-jpa.yml"
      - "classpath:application-monitoring.yml"

server:
  port: 10011
