spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER_1},${KAFKA_BROKER_2},${KAFKA_BROKER_3}
    consumer:
      group-id: ${spring.application.name}-group
      properties:
        spring.json.trusted.packages: '*'

logging:
  level:
    org.springframework.kafka.listener.KafkaMessageListenerContainer: OFF