spring:
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: ${spring.application.name}-group
      properties:
        spring.json.trusted.packages: '*'

logging:
  level:
    org.springframework.kafka.listener.KafkaMessageListenerContainer: OFF