spring:
  application:
    name: queue-manage

  config:
    import:
      - "classpath:application-eureka.yml"
      - "classpath:application-redis.yml"
      - "classpath:application-kafka.yml"
      - "classpath:application-monitoring.yml"

server:
  port: 10015

token-value:
  secret-key: secret-key

working-queue:
  max-size: 1000
  token-ttl: 30