spring:
  application:
    name: queue-manage

  data:
    redis:
      cluster:
        nodes:
          - host.docker.internal:7001
          - host.docker.internal:7002
          - host.docker.internal:7003
          - host.docker.internal:7004
          - host.docker.internal:7005
          - host.docker.internal:7006

  config:
    import:
      - "classpath:application-kafka.yml"

server:
  port: 10031

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:10000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  prometheus:
    enabled: true

token-value:
  secret-key: secret-key

working-queue:
  max-size: 1000
  token-ttl: 30