spring:
  application:
    name: queue-manage

  config:
    import:
      - "classpath:application-redis.yml"
      - "classpath:application-kafka.yml"

server:
  port: 10015

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:10000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  prometheus:
    enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.ticketPing.queue_manage
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

token-value:
  secret-key: secret-key

working-queue:
  max-size: 1000
  token-ttl: 30