spring:
  application:
    name: queue-manage

  config:
    import:
      - "classpath:application-eureka.yml"
      - "classpath:application-redis.yml"
      - "classpath:application-kafka.yml"
      - "classpath:application-monitoring.yml"

server:
  port: 10015

token-value:
  secret-key: ${USER_TOKEN_SECRET_KEY}

working-queue:
  max-size: ${WORKING_QUEUE_MAX_SIZE}
  initial-token-ttl: ${INITIAL_WORKING_QUEUE_TOKEN_TTL}
  extended-token-ttl: ${EXTENDED_WORKING_QUEUE_TOKEN_TTL}