spring:
  application:
    name: queue-manage

  data:
    redis:
      cluster:
        nodes:
          - host.docker.internal:7001
          - host.docker.internal:7002
          - host.docker.internal:7003
          - host.docker.internal:7004
          - host.docker.internal:7005
          - host.docker.internal:7006

  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: ${spring.application.name}-group
      properties:
        spring.json.trusted.packages: '*'

server:
  port: 10031

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:10000/eureka/

token-value:
  secret-key: secret-key

working-queue:
  max-size: 1000
  token-ttl: 30

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  prometheus:
    enabled: true
