spring:
  application:
    name: queue-manage

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}-group
      properties:
        spring.json.trusted.packages: '*'

server:
  port: 10031

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/

token-value:
  secret-key: secret-key

working-queue:
  max-size: 1000
  token-ttl: 30

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  prometheus:
    enabled: true
